### ISSUE TITLE
Bitwise and simplifier can reduce bitvector size

### ISSUE THREAD

**Issue by tgduckworth** [angr/claripy#126]
**Describe the bug**
Performing a bitwise and on two bitvectors of the same length may cause the result to be shorter than the operands are. My suspicion is that this problem arises when [this](https://github.com/angr/claripy/blob/ca524cb2af19952d247ff072b38140b4eb8d21c1/claripy/simplifications.py#L536) condition and the one that follows are both true and when the number of arguments to the concat AST is greater than two. This simplification seems to operate under the assumption that there will only ever be two arguments, but when using angr this does not always seem to be the case.

**Environment Information**
```plain
$ python -m angr.misc.bug_report
angr environment report
=============================
Date: 2019-01-30 17:55:16.751118
Running in virtual environment at /home/tgduckworth/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
######## angr #########
Python found it in /home/tgduckworth/dev/angr-dev/angr/angr
Pip version angr 8.18.10.25
Git info:
    Current commit 865a5dc0a5695cba4cbf79a91a171e7fb8d460cb from branch master
    Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/tgduckworth/dev/angr-dev/ailment/ailment
Pip version ailment 8.18.10.25
Git info:
    Current commit 284a67b1b5db5c950bebf4b6a096a127318474e8 from branch master
    Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/tgduckworth/dev/angr-dev/cle/cle
Pip version cle 8.18.10.25
Git info:
    Current commit 28cbf5c5888b374b173410ef2e508b4eab7c02aa from branch master
    Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/tgduckworth/dev/angr-dev/pyvex/pyvex
Pip version pyvex 8.18.10.25
Git info:
    Current commit 36ba7fefbece6c11a27933b5151b450a87856302 from branch master
    Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/tgduckworth/dev/angr-dev/claripy/claripy
Pip version claripy 8.18.10.25
Git info:
    Current commit 16457ff5b60f348b9246d4e2df4ff62052f89cc6 from branch master
    Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/tgduckworth/dev/angr-dev/archinfo/archinfo
Pip version archinfo 8.18.10.25
Git info:
    Current commit bbac424873989d9cc4ce3ed01b7003ace04b4756 from branch master
    Checked out from remote origin: https://github.com/angr/archinfo
######## ana #########
Python found it in /home/tgduckworth/.virtualenvs/angr/lib/python3.5/site-packages/ana
Pip version ana 0.5
Couldn't find git info
######## z3 #########
Python found it in /home/tgduckworth/.virtualenvs/angr/lib/python3.5/site-packages/z3
Pip version not found!
Couldn't find git info
######## unicorn #########
Python found it in /home/tgduckworth/.virtualenvs/angr/lib/python3.5/site-packages/unicorn
Pip version unicorn 1.0.1
Couldn't find git info
######### Native Module Info ##########
z3: <CDLL '/home/tgduckworth/.virtualenvs/angr/lib/python3.5/site-packages/z3/lib/libz3.so', handle 38f6e20 at 0x7fd4c9fed668>
unicorn: <CDLL '/home/tgduckworth/.virtualenvs/angr/lib/python3.5/site-packages/unicorn/lib/libunicorn.so', handle 28c1000 at 0x7fd4c76ecef0>
angr: <CDLL '/home/tgduckworth/dev/angr-dev/angr/angr/lib/angr_native.so', handle 2f4c7c0 at 0x7fd4c3cb3ac8>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fd4c836cb70>
```

**To Reproduce**
```python
import angr

malloc = angr.SIM_PROCEDURES['libc']['malloc']()
proj = angr.Project("/bin/true", auto_load_libs=False)
s = proj.factory.blank_state()
p = malloc.execute(s, arguments=[40]).ret_expr
v = s.solver.BVS("v", 32)
s.memory.store(p, v)

# loading preserves value
x = s.memory.load(p, 4)
assert s.solver.is_true(x == v)

# let's modify the middle of it
y = s.memory.load(p, 2)
y = y | 0x10
print(y)  # <BV16 v_2_32[31:16] | 0x10>
s.memory.store(p, y)

# we now have a concat with three args
z = s.memory.load(p, 4)
assert z.op == "Concat"
assert len(z.args) == 3
print(z)  # <BV32 v_2_32[31:21] .. 1 .. v_2_32[19:0]>

# an operand of no particular significance
b = s.solver.BVV(2 ** (z.size() - z.args[0].size()) - 1, 32)
assert s.solver.is_true(b == 0x1fffff)
print(b)  # <BV32 0x1fffff>

trouble = z & b
print(trouble)  # <BV12 0x1>
s.memory.store(p, trouble)

# Traceback (most recent call last):
#   File "/home/tgduckworth/dev/misc/claripy_bug.py", line 35, in <module>
#     s.memory.store(p, trouble)
#   File "/home/tgduckworth/dev/angr-dev/angr/angr/storage/memory.py", line 516, in store
#     raise SimMemoryError("Attempting to store non-byte data to memory")
# angr.errors.SimMemoryError: Attempting to store non-byte data to memory
```

**Additional context**
I'm not too familiar with the design of claripy, so I'm not sure whether this is a problem with the claripy simplifier or whether concat is supposed to be a binary operator, with angr incorrectly constructing concat ASTs with more than two arguments. I suspect it is the former, but wanted to open this issue for discussion with someone who might be able to hone in on the problem a bit further.

**Comment by ltfish** [comment]
It's definitely a bug... will be fixed soon!

**Comment by rhelmot** [comment]
Yeah, concat is meant to have variadic arguments, and this simplifier assumed otherwise (git blame says: thanks fish). thanks for reporting!
