### ISSUE TITLE
`test_solver.test_unsat_core` is failing on `master`

### ISSUE THREAD

**Issue by Pamplemousse** [angr/claripy#179]
```
$ nose2 -s tests/ test_solver.test_unsat_core
...E....
======================================================================
ERROR: test_solver.test_unsat_core:4
<class 'claripy.solvers.SolverComposite'>, False
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pamplemousse/Workspace/angr/claripy/tests/test_solver.py", line 534, in raw_unsat_core
    unsat_core = s.unsat_core()
  File "/home/pamplemousse/Workspace/angr/claripy/claripy/frontends/composite_frontend.py", line 368, in unsat_core
    cores.extend(list(solver.unsat_core(extra_constraints=extra_constraints)))
  File "/home/pamplemousse/Workspace/angr/claripy/claripy/frontends/full_frontend.py", line 210, in unsat_core
    unsat_core = self._solver_backend.unsat_core(self._get_solver())
  File "/home/pamplemousse/Workspace/angr/claripy/claripy/backends/__init__.py", line 466, in unsat_core
    return [ self._abstract(core) for core in self._unsat_core(s) ]
  File "/home/pamplemousse/Workspace/angr/claripy/claripy/backends/__init__.py", line 466, in <listcomp>
    return [ self._abstract(core) for core in self._unsat_core(s) ]
  File "/home/pamplemousse/Workspace/angr/claripy/claripy/backends/backend_z3.py", line 70, in z3_condom
    return f(*args, **kwargs)
  File "/home/pamplemousse/Workspace/angr/claripy/claripy/backends/backend_z3.py", line 393, in _abstract
    return self._abstract_internal(e.ctx.ctx, e.ast)
AttributeError: 'NoneType' object has no attribute 'ctx'
```

**Comment by rhelmot** [comment]
This testcase is nondeterministic and based on garbage collection patterns I believe. It is passing fairly consistently on CI..
