### ISSUE TITLE
Unable to import claripy in MAC

### ISSUE THREAD

**Issue by H4rryp0tt3r** [angr/claripy#6]
I installed claripy with pip using <code>pip install claripy</code>

After installation, I tried importing it and then I got this error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/claripy/__init__.py", line 17, in <module>
    from . import backends as _backends_module
  File "/Library/Python/2.7/site-packages/claripy/backends/__init__.py", line 1, in <module>
    from .backend_z3 import BackendZ3
  File "/Library/Python/2.7/site-packages/claripy/backends/backend_z3.py", line 43, in <module>
    z3.init(z3_path)
AttributeError: 'module' object has no attribute 'init'

**Comment by ltfish** [comment]
I'm not sure how to solve it since none of us developers uses OS X. Can you please try the following to recompile Z3 library and let me know if it works?

```
pip install -I --no-use-wheel angr-only-z3-custom
```
